trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    -  repository: azure-iot-platform-dotnet
       name: MMM\azure-iot-platform-dotnet
       ref: blue-green-poc

jobs:
  - job: serviceCreationHelm
    steps:
      - checkout:  azure-iot-platform-dotnet

      - task: HelmDeploy@0
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: '3M-CRSLAD16-BBIoTP-Dev'
          azureResourceGroup: 'rg-iot-ggk-dev'
          kubernetesCluster: 'ggktech-aks-dev'
          namespace: 'default'
          command: 'install'
          chartType: 'FilePath'
          chartPath: 'charts/mmm-iot-service'
          releaseName: 'asa-manager-service'
          overrideValues: 'nameOverride=asa-manager-test,service.port=80,type=blue,selectOverride=blue,deployment.enabled=false,service.enabled=true'

    