trigger: none
pr: none
resources:
  pipelines:
    - pipeline: test
      source: azure-iot-platform-dotnet.ci.test
      trigger:
        branches:
          - master
pool:
  vmImage: ubuntu-latest
variables:
  ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
    _imageTag: $(resources.pipeline.test.runID)
  ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
    _imageTag: $(imageTag)
stages:
  - stage: checkParameters
    displayName: Check parameters
    dependsOn: []
    jobs:
      - job: checkParameters
        displayName: Check parameters
        steps:
          - checkout: none

          - script: |-
              set -Eeuxo pipefail
              echo "Image tag: '$(_imageTag)'"
              if [ -z "$(_imageTag)" ]
              then
                echo "A value for the 'imageTag' variable must be provided" > /dev/stderr
                exit 1
              fi
            displayName: Check parameters

  - stage: printPipelineResourceVariables
    displayName: Print pipeline resource variables
    dependsOn: []
    jobs:
      - job: printPipelineResourceVariables
        displayName: Print pipeline resource variables
        steps:
          - checkout: none

          - template: ../templates/print-pipeline-resource-variables.yaml
            parameters:
              pipelineResourceName: test


  - stage: ggkDev
    displayName: GGK dev
    dependsOn:
      - checkParameters
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: GGK-Environment
          subscriptionName: 3M-CRSLAD16-BBIoTP-DEV
          applicationCode: ggktech
          applicationShortCode: ggk
          environmentCategory: dev
          imageTag: $(_imageTag)
          subscriptionId: c36fb2f8-f98d-40d0-90a9-d65e93acb428
