trigger: none
pr: none
resources:
  pipelines:
    - pipeline: test
      source: azure-iot-platform-dotnet.ci.test
      trigger:
        branches:
          - master
pool:
  vmImage: ubuntu-latest
variables:
  ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
    _imageTag: $(resources.pipeline.test.runID)
  ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
    _imageTag: $(imageTag)
stages:
  - stage: checkParameters
    displayName: Check parameters
    dependsOn: []
    jobs:
      - job: checkParameters
        displayName: Check parameters
        steps:
          - checkout: none

          - script: |-
              set -Eeuxo pipefail
              echo "Image tag: '$(_imageTag)'"
              if [ -z "$(_imageTag)" ]
              then
                echo "A value for the 'imageTag' variable must be provided" > /dev/stderr
                exit 1
              fi
            displayName: Check parameters

  - stage: printPipelineResourceVariables
    displayName: Print pipeline resource variables
    dependsOn: []
    jobs:
      - job: printPipelineResourceVariables
        displayName: Print pipeline resource variables
        steps:
          - checkout: none

          - template: ../templates/print-pipeline-resource-variables.yaml
            parameters:
              pipelineResourceName: test

  - stage: emdDev
    displayName: EMD dev
    dependsOn:
      - checkParameters
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_EMD_Environment_DEV
          subscriptionName: 3M-UDAH02-SpartanIotHub-Dev
          applicationCode: emdiot
          applicationShortCode: emd
          environmentCategory: dev
          imageTag: $(_imageTag)
          blueGreen: false
          subscriptionId: 191495e8-b878-4140-85eb-aae73a7119cd

  - stage: emdQa
    displayName: EMD QA
    dependsOn:
      - emdDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_EMD_Environment_QA
          subscriptionName: 3M-UDAH03-SpartanIotHub-QA
          applicationCode: emdiot
          applicationShortCode: emd
          environmentCategory: qa
          imageTag: $(_imageTag)
          blueGreen: false
          subscriptionId: 5248a0ea-c79b-4739-adc7-e76eeb27e253

  - stage: emdCt
    displayName: EMD CT
    dependsOn:
      - emdQa
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_EMD_Environment_CT
          subscriptionName: 3M-UDAH04-SpartanIotHub-CT
          applicationCode: emdiot
          applicationShortCode: emd
          environmentCategory: ct
          imageTag: $(_imageTag)
          blueGreen: false
          subscriptionId: e9f61243-5e9a-4b8a-918c-09fe7e9f1ec1
