trigger: none
pr: none
resources:
  pipelines:
    - pipeline: test
      source: azure-iot-platform-dotnet.ci.test
      trigger:
        branches:
          - master
pool:
  vmImage: ubuntu-latest
variables:
  ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
    _imageTag: $(resources.pipeline.test.runID)
  ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
    _imageTag: $(imageTag)
stages:
  - stage: checkParameters
    displayName: Check parameters
    dependsOn: []
    jobs:
      - job: checkParameters
        displayName: Check parameters
        steps:
          - checkout: none

          - script: |-
              set -Eeuxo pipefail
              echo "Image tag: '$(_imageTag)'"
              if [ -z "$(_imageTag)" ]
              then
                echo "A value for the 'imageTag' variable must be provided" > /dev/stderr
                exit 1
              fi
            displayName: Check parameters

  - stage: printPipelineResourceVariables
    displayName: Print pipeline resource variables
    dependsOn: []
    jobs:
      - job: printPipelineResourceVariables
        displayName: Print pipeline resource variables
        steps:
          - checkout: none

          - template: ../templates/print-pipeline-resource-variables.yaml
            parameters:
              pipelineResourceName: test

  - stage: psdDev
    displayName: PSD dev
    dependsOn:
      - checkParameters
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_PSD_Environment_DEV
          subscriptionName: 3M-ASDT04-PSD-CS-IOT-Dev
          applicationCode: psdiot
          applicationShortCode: psd
          environmentCategory: dev
          imageTag: $(_imageTag)
          blueGreen: false
          subscriptionId: 1d0a4e20-e44d-43b5-97b0-9b577f5bf048

  - stage: psdQa
    displayName: PSD QA
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_PSD_Environment_QA
          subscriptionName: 3M-ASDT05-PSD-CS-IOT-QA
          applicationCode: psdiot
          applicationShortCode: psd
          environmentCategory:  qa
          imageTag: $(_imageTag)
          blueGreen: false
          subscriptionId: 8c550fc0-24e0-43cb-8237-5fbb168c1071

  - stage: psdEu
    displayName: PSD EU
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_PSD_Environment_EU
          subscriptionName: 3M-ASDT07-PSD-CS-IOT-Prod
          applicationCode: psdiot
          applicationShortCode: psd
          environmentCategory: eu
          imageTag: $(_imageTag)
          blueGreen: false
          subscriptionId: 71fd3c60-f2c3-4e78-ad18-7e370fe3b068

  - stage: psdStg
    displayName: PSD staging
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_PSD_Environment_STG
          subscriptionName: 3M-ASDT05-PSD-CS-IOT-QA
          applicationCode: psdiot
          applicationShortCode: psd
          environmentCategory: stg
          imageTag: $(_imageTag)
          blueGreen: false
          subscriptionId: 8c550fc0-24e0-43cb-8237-5fbb168c1071

  - stage: psdProd
    displayName: PSD Prod
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_PSD_Environment_Prod
          subscriptionName: 3M-ASDT07-PSD-CS-IOT-Prod
          applicationCode: psdiot
          applicationShortCode: psd
          environmentCategory: prod
          imageTag: $(_imageTag)
          blueGreen: false
          subscriptionId: 71fd3c60-f2c3-4e78-ad18-7e370fe3b068
