trigger: none
pr: none
resources:
  pipelines:
    - pipeline: test
      source: azure-iot-platform-dotnet.ci.test
      project: AzurePlatform
      trigger:
        stages:
          - listCommitsSinceLastRelease
        branches:
          - master
stages:
  - stage: Stage1
    displayName: Print
    dependsOn: []
    jobs:
      - job: Print
        displayName: Print
        steps:
          - checkout: none

          - script: |-
              set -Eeuxo pipefail
              echo "envName: '$(envName)'"
              echo "envCategory": '$(envCategory)'
              if [ -z "$(envName)" ]
              then
                echo "A value for the 'envName' variable must be provided" > /dev/stderr
                exit 1
              fi
              if [ -z "$(envCategory)" ]
              then
                echo "A value for the 'envCategory' variable must be provided" > /dev/stderr
                exit 1
              fi
            displayName: Print
