trigger: none
pr: none
pool:
  vmImage: ubuntu-latest
variables:
  locationName: centralus
  ${{ if eq(variables['Build.Reason'], 'ResourceTrigger') }}:
    _runVersion: latestFromBranch
    _testPipelineRunId: n/a
  ${{ if ne(variables['Build.Reason'], 'ResourceTrigger') }}:
    _runVersion: specific
    _testPipelineRunId: $(testPipelineRunId)
stages:
  - stage: checkParameters
    displayName: Check parameters
    dependsOn: []
    jobs:
      - job: checkParameters
        displayName: Check parameters
        steps:
          - checkout: none

          - script: |-
              echo "Test pipeline run ID: '$(_testPipelineRunId)'"
              if [ -z "$(_testPipelineRunId)" ]
              then
                echo "A value for the 'testPipelineRunId' variable must be provided" > /dev/stderr
                exit 1
              fi
            displayName: Check parameters

  - stage: printPipelineResourceVariables
    displayName: Print pipeline resource variables
    dependsOn: []
    jobs:
      - job: printPipelineResourceVariables
        displayName: Print pipeline resource variables
        steps:
          - checkout: none

          - template: ../templates/print-pipeline-resource-variables.yaml
            parameters:
              pipelineResourceName: test